### PR TITLE
New schedule

### PR DESCRIPTION
**Pull request by dwfreed**
Update for the new schedule.  This merges all the other pull requests into one.  I'd ask to take over maintaining this, but very soon I probably won't be able to, so I'll hold off until I know one way or the other.

### CODE REVIEW

**Comment by Katharine** [comment]
@dwfreed What data file does this use? The last version I tried pulling was broken, and Caltrain has since withdrawn it entirely.

**Comment by dwfreed** [comment]
I wrote my own; I can provide you with the files if you'd like.

**Comment by Katharine** [comment]
I would be interested to see them. What did you use as the source material?

**Comment by dwfreed** [comment]
The web schedule, and pulled bits and pieces from old GTFS files I had lying around or were available on the Internet (there's a site that archives them).

**Comment by dwfreed** [comment]
https://gist.github.com/dwfreed/c59f1b13be8afc6ec338d5dc1d6f8567

**Pull request merged**
